---
- name: Ensure OpenVPN is installed
  apt:
    name: openvpn
    state: present
    update_cache: yes

- name: Download EasyRSA
  get_url:
    url: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz"
    dest: /tmp/EasyRSA-3.0.8.tgz

- name: Extract EasyRSA
  unarchive:
    src: /tmp/EasyRSA-3.0.8.tgz
    dest: /etc/openvpn
    remote_src: yes

- name: Move EasyRSA directory
  command: mv /etc/openvpn/EasyRSA-3.0.8 /etc/openvpn/easy-rsa

- name: Generate random passphrase for CA
  set_fact:
    ca_passphrase: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters') }}"

- name: Save CA passphrase to file
  copy:
    content: "{{ ca_passphrase }}"
    dest: /etc/openvpn/easy-rsa/ca_passphrase.txt
    mode: '0600'

- name: Initialize the PKI directory
  command: ./easyrsa init-pki
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Build CA
  command: ./easyrsa --batch --req-cn="OpenVPN-CA" build-ca nopass
  args:
    chdir: /etc/openvpn/easy-rsa
  environment:
    EASYRSA_PASSOUT: "pass:{{ ca_passphrase }}"

- name: Generate server certificate and key
  command: ./easyrsa --batch --req-cn="server" build-server-full server nopass
  args:
    chdir: /etc/openvpn/easy-rsa
  environment:
    EASYRSA_PASSIN: "pass:{{ ca_passphrase }}"

- name: Generate Diffie-Hellman parameters
  command: ./easyrsa gen-dh
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Copy server certificates and keys
  copy:
    src: /etc/openvpn/easy-rsa/pki/issued/server.crt
    dest: /etc/openvpn/server.crt

- name: Copy server key
  copy:
    src: /etc/openvpn/easy-rsa/pki/private/server.key
    dest: /etc/openvpn/server.key

- name: Copy CA certificate
  copy:
    src: /etc/openvpn/easy-rsa/pki/ca.crt
    dest: /etc/openvpn/ca.crt

- name: Copy DH parameters
  copy:
    src: /etc/openvpn/easy-rsa/pki/dh.pem
    dest: /etc/openvpn/dh.pem

- name: Configure OpenVPN
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf

- name: Enable and start OpenVPN service
  systemd:
    name: openvpn@server
    state: started
    enabled: yes

- name: Restart OpenVPN service
  systemd:
    name: openvpn@server
    state: restarted
    when: restart_openvpn is defined and restart_openvpn
