---
- name: Ensure OpenVPN is installed
  apt:
    name: openvpn
    state: present
    update_cache: yes

- name: Download EasyRSA
  get_url:
    url: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz"
    dest: /tmp/EasyRSA-3.0.8.tgz

- name: Extract EasyRSA
  unarchive:
    src: /tmp/EasyRSA-3.0.8.tgz
    dest: /etc/openvpn
    remote_src: yes

- name: Move EasyRSA directory
  command: mv /etc/openvpn/EasyRSA-3.0.8 /etc/openvpn/easy-rsa

- name: Initialize the PKI directory
  command: ./easyrsa init-pki
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Build CA
  command: ./easyrsa build-ca nopass
  args:
    chdir: /etc/openvpn/easy-rsa
  environment:
    EASYRSA_BATCH: "1"
    EASYRSA_REQ_CN: "OpenVPN-CA"

- name: Generate server certificate and key
  command: ./easyrsa build-server-full server nopass
  args:
    chdir: /etc/openvpn/easy-rsa
  environment:
    EASYRSA_BATCH: "1"
    EASYRSA_REQ_CN: "server"

- name: Generate Diffie-Hellman parameters
  command: ./easyrsa gen-dh
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Copy server certificates and keys
  copy:
    src: /etc/openvpn/easy-rsa/pki/issued/server.crt
    dest: /etc/openvpn/server.crt
  notify: Restart OpenVPN

- name: Copy server key
  copy:
    src: /etc/openvpn/easy-rsa/pki/private/server.key
    dest: /etc/openvpn/server.key
  notify: Restart OpenVPN

- name: Copy CA certificate
  copy:
    src: /etc/openvpn/easy-rsa/pki/ca.crt
    dest: /etc/openvpn/ca.crt
  notify: Restart OpenVPN

- name: Copy DH parameters
  copy:
    src: /etc/openvpn/easy-rsa/pki/dh.pem
    dest: /etc/openvpn/dh.pem
  notify: Restart OpenVPN

- name: Configure OpenVPN
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  notify: Restart OpenVPN

- name: Enable and start OpenVPN service
  systemd:
    name: openvpn@server
    state: started
    enabled: yes
