---
- name: Generate client certificate and key
  command: ./easyrsa build-client-full {{ openvpn_client_name }} nopass
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/{{ openvpn_client_name }}.crt
  environment:
    EASYRSA_BATCH: "1"
    EASYRSA_REQ_CN: "{{ openvpn_client_name }}"
    EASYRSA_PASSIN: "pass:{{ ca_passphrase }}"

- name: Create client configuration directory
  file:
    path: /etc/openvpn/client
    state: directory
    mode: '0755'

- name: Retrieve client configuration
  shell: |
    cat /etc/openvpn/easy-rsa/pki/ca.crt \
        /etc/openvpn/easy-rsa/pki/issued/{{ openvpn_client_name }}.crt \
        /etc/openvpn/easy-rsa/pki/private/{{ openvpn_client_name }}.key > /etc/openvpn/client/{{ openvpn_client_name }}.ovpn
  register: ovpn_file_content

- name: Create client configuration template
  template:
    src: client.ovpn.j2
    dest: /etc/openvpn/client/{{ openvpn_client_name }}.ovpn

- name: Save .ovpn file to localhost
  copy:
    src: /etc/openvpn/client/{{ openvpn_client_name }}.ovpn
    dest: "./{{ openvpn_client_name }}.ovpn"
