---
- name: Generate client certificate and key using expect
  expect:
    command: ./easyrsa build-client-full {{ openvpn_client_name }} nopass
    chdir: /etc/openvpn/easy-rsa
    responses:
      'Enter PEM pass phrase:': "{{ ca_passphrase }}\n"
      'Verifying - Enter PEM pass phrase:': "{{ ca_passphrase }}\n"
      'Common Name (eg: your user, host, or server name) [{{ openvpn_client_name }}]:': "{{ openvpn_client_name }}\n"

- name: Create client configuration directory
  file:
    path: /etc/openvpn/client
    state: directory
    mode: '0755'

- name: Retrieve client configuration
  shell: |
    cat /etc/openvpn/easy-rsa/pki/ca.crt \
        /etc/openvpn/easy-rsa/pki/issued/{{ openvpn_client_name }}.crt \
        /etc/openvpn/easy-rsa/pki/private/{{ openvpn_client_name }}.key > /etc/openvpn/client/{{ openvpn_client_name }}.ovpn
  register: ovpn_file_content

- name: Create client configuration template
  template:
    src: client.ovpn.j2
    dest: /etc/openvpn/client/{{ openvpn_client_name }}.ovpn

- name: Save .ovpn file to localhost
  copy:
    src: /etc/openvpn/client/{{ openvpn_client_name }}.ovpn
    dest: "./{{ openvpn_client_name }}.ovpn"
