---
- name: Generate random port for OpenVPN
  set_fact:
    openvpn_port: "{{ 49152 | random(seed=inventory_hostname) | int + (65535-49152) }}"

- name: Pull and run OpenVPN Docker container
  command: docker-compose -f /srv/docker-compose.yml up -d
