---
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure Docker Compose is installed
  pip:
    name: docker-compose
    state: present

- name: Deploy Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /srv/docker-compose.yml
